# Generated by Django 2.2.6 on 2019-10-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=45)),
                ('done_interview', models.BooleanField()),
                ('resume', models.CharField(max_length=100)),
                ('transcript', models.CharField(max_length=100)),
            ],
        ),
    ]
