# Generated by Django 2.2.6 on 2019-10-19 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporation',
            old_name='hired',
            new_name='num_hired',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student',
        ),
        migrations.AddField(
            model_name='application',
            name='user_created',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.User', verbose_name='User that created application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporation',
            name='new_hires',
            field=models.ManyToManyField(to='management.User'),
        ),
    ]
